- name: vars from prompt
  hosts: localhost
  vars_prompt:
  - name: USERNAME
    prompt: please enter username
    private: false
  - name: PASSWORD
    prompt: please enter password
    private: true
  - tasks:
    ansible.builtin.debug:
      msg: "username: {{USERNAME}}, password: {{PASSWORD}}"