- name: variables from inventory
  hosts: mongodb
  mongodb:vars
  - MONGO_USERNAME: mongodbadmin
    MONGO_DB: categories
  tasks:
  - name: print mongodb username
    ansible.builtin.debug:
      msg: "username is: {{MONGO_USERNAME}}"