- name: testing variable precedence
  hosts: mongodb
  vars:
    NAME: sahith play
  vars_files: 
  - variables.yaml
  vars_prompt:
  - name: NAME
    prompt: please enter trainer name
    private: false
  tasks:
  - name: variable at task level
    vars:
      NAME: sahith posa
    ansible.builtin.debug:
      msg: "trainer name is: {{NAME}}"