- name: install packages
  hosts: localhost
  become: yes
  tasks:
  - name: install package
    ansible.builtin.yum:
      name: "{{item.name}}"
      state: installed
    loop:
    - {name: 'nginx', state: 'absent'}
    - {name: 'postfix', state: 'installed'}
    - {name: 'cyrus-sasl-plain', state: 'installed'}
    - {name: 'mailx', state: 'absent'}